### ISSUE TITLE
Can there be more tolerance if the patterns are very similar?

### ISSUE THREAD

**Issue by crapthings** [gemini-testing/looks-same#100]
<img width="1658" alt="image" src="https://github.com/gemini-testing/looks-same/assets/1147704/801132cd-1c70-4302-a9b1-eb083db9742c">

i m using this for now, but the block is very hard to solve like this image

```
const { equal } = await looksSame(image1, image2)
```

what is tolerance value for such scene?

```
const {equal} = await looksSame('image1.png', 'image2.png', {tolerance: 5});
```

**Comment by DudaGod** [comment]
Hello. I didn't understand your question. I see one image with strange hand-drawn rings. And I don’t see the image with which it is compared. Can you send images separately from each other? 

in most cases it is recommended to use tolerance with `2.3` (with this value the eye does not see the difference between images).

**Comment by crapthings** [comment]
i'm making a puzzle game

<img width="2193" alt="image" src="https://github.com/gemini-testing/looks-same/assets/1147704/17759c33-ce5a-4c87-9c87-d39e71af4fda">


the problem is this piece is very hard to solve, because solid color looks same

https://www.text2puzzles.com/solve/2d8f81ef-46b7-425a-aed8-364f0e6d3847-u1

**Comment by crapthings** [comment]
> Hello. I didn't understand your question. I see one image with strange hand-drawn rings. And I don’t see the image with which it is compared. Can you send images separately from each other?
> 
> in most cases it is recommended to use tolerance with `2.3` (with this value the eye does not see the difference between images).

i will try~

**Comment by DudaGod** [comment]
> tried to 5 but still not equal

Of course they are not the same. I can see the difference with my eye without any approximation.

You need to either take a reference after cutting the image or use another validation mechanism (I wrote the options above).

**Comment by DudaGod** [comment]
It seems that the problem has been sorted out here. No problems were found with the looks-same. In your place, I would use this option:

> Perhaps with canvas you can assign IDs to each piece of the puzzle and validate their correctness by position. But in this case it is necessary that each piece be different from each other (for example, add uniqueness by connecting elements, like in real puzzles).
