### ISSUE TITLE
ignoreAntialiasing not work in ie10 screen shot

### ISSUE THREAD

**Issue by bindoon** [gemini-testing/looks-same#22]
- ref
![ie10 ref](https://cloud.githubusercontent.com/assets/5189853/21512566/e13f6c56-cce9-11e6-97bc-8e234e4ea93d.png)

- current

![ie10 current](https://cloud.githubusercontent.com/assets/5189853/21512568/ed4f18c0-cce9-11e6-98e5-3cbc149c6779.png)

- diff

![ie10 diff](https://cloud.githubusercontent.com/assets/5189853/21512570/f29d97c0-cce9-11e6-94e4-dcdf72dc1d1a.png)

**Comment by bindoon** [comment]
@sipayRT can you hava a look?

**Comment by sipayRT** [comment]
let's discuss it in gemini repo - https://github.com/gemini-testing/gemini/issues/709#issuecomment-274759359
