### ISSUE TITLE
Compare images as Buffers

### ISSUE THREAD

**Issue by RedHatter** [gemini-testing/looks-same#44]
Can you add an option to compare two images from buffers instead of files? With my use case I generate the images and it would be nice to not have to save to a temporary file to compare them.

**Comment by RedHatter** [comment]
Nevermind. It looks like that functionality already exists. Maybe document it?

**Comment by shenjiayi1993** [comment]
Hi, do you know how to use it? Thanks.

**Comment by crapthings** [comment]
how to use it?
what if i fetch image from url

my use case is one from s3, one from user input base64

i've tried

```
axios.get as arraybuffer and buffer.from(input, 'base64')
```

**Comment by crapthings** [comment]
its working after remove base64 header

```js
const url = your image url here
const resp = await axios.get(url, { responseType: 'arraybuffer' })
const image1 = resp.data
const image2 = Buffer.from(data.input.split(',').pop(), 'base64')
const { equal } = await looksSame(resp.data, image2)
```

**Comment by DudaGod** [comment]
Looks-same can compare buffers, example:
```
const {equal} = await looksSame(buff1, buff2);
```
