### ISSUE TITLE
Looks-same to return the diff as a base64 string

### ISSUE THREAD

**Issue by flore77** [gemini-testing/looks-same#5]
## Need

```
As a developer
I need to have a pluggable application 
So that I can build and manage other application on top of it
```

It would be nice to have a method that returns the `diff` as  a `base64 String`, so the developer can manage it how he wants, to store it into a database, to send it to a server etc.

## Deliverables

* implement the method
* add tests

## Solution

`add a method` to the the `prototype` of `PNGOut`:

```js
  /**
  * @param {base64Cb} callback
  */
  createBuffer: function(callback) {
    this._png.pack(); // behaves like a stream
    
    // collect the data on 'data' events
    // on end event call the callback
    callback(null, buffer);
  }

  /**
  * @callback base64Cb
  * @param error
  * @param {Buffer} buffer
  */
```

adding another option to the options passed to createDiff function:

```js
  /**
  * @param {Object} options
  * @param {Boolean} [options.save]
  */
  createDiff(options, callback) {}
```

the callback passed to `buildDiffImage`, may look like:

```js
function(result) {
  if (opts.save) {
    result.save(opts.path, callback);
  }
  else {
   result.createBase64(callback);
  }
}

**Comment by flore77** [comment]
what do you say ? @SevInf

**Comment by SevInf** [comment]
I like the idea, but considering we are in a node environment, returning `Buffer` seems like more useful option. Buffers can easily be converted to base64 (`buffer.toString('base64')`), but also can be easily saved to binary files or passed to various image manipulation libraries without a conversion from string.

**Comment by flore77** [comment]
Yes, you are right, it is better to return a buffer. I have updated the specs. I will fork the repo, write the code and I will do a pull request. thanks for quick reply!
