### ISSUE TITLE
pngjs is outdated and buggy consider switching to pngjs2

### ISSUE THREAD

**Issue by lukeapage** [gemini-testing/looks-same#8]
You may want to consider upgrading to pngjs2 - it has the same API, but has bug fixes merged and far better support for PNG's (e.g. interlaced, 1/2/4/16 bit, transparent colours etc.)

**Comment by SevInf** [comment]
Thanks for suggestion. It looks like we can also replace `pngparse` with it as well — the only reason we use different libs for reading and writing files is necessity to support non-32bit pngs.

**Comment by lukeapage** [comment]
yes, I've ported the pngparse tests - I didn't realise you were using both.

**Comment by LinusU** [comment]
@lukeapage Have you tried getting npm to giving you the original name (`pngjs`)? Their policy is to transfer the name if the original owner isn't around to push new releases.

[NPM: Handling Module Name Disputes](https://docs.npmjs.com/misc/disputes)

**Comment by lukeapage** [comment]
@LinusU thanks for the tip, I've started that process

**Comment by LinusU** [comment]
@lukeapage That's awesome! :tada:

**Comment by LinusU** [comment]
@lukeapage Any updates? :8ball:

**Comment by lukeapage** [comment]
I have control of pngjs, but I haven't published yet. I mean to (it will be v2), I've just been busy. will update you soon.

**Comment by LinusU** [comment]
Glad to hear it :)

**Comment by LinusU** [comment]
Oh, actually, I have released some node.js bindings for lodepng which is an awesome png library. If this is only intended for server side it's probably faster than a javascript implementation.

https://github.com/LinusU/node-lodepng

**Comment by lukeapage** [comment]
I have now published pngjs, version 2

**Comment by SevInf** [comment]
Closed in 2.2.2
