### ISSUE TITLE
How to compare network images？

### ISSUE THREAD

**Issue by SheepYang1993** [gemini-testing/looks-same#87]

**Comment by DudaGod** [comment]
Hello.

You should download them to your file system before compare.

**Comment by Noonlord** [comment]
You can read them to buffer. 

`export const compareImages = async (img1: string, img2: string): Promise<boolean> => {
  // read images from internet
  const [img1Resp, img2Resp] = await Promise.all([axios.get(img1, { responseType: "arraybuffer" }), axios.get(img2, { responseType: "arraybuffer" })]);
  // convert them to buffer
  const img1Buffer = Buffer.from(img1Resp.data, "binary");
  const img2Buffer = Buffer.from(img2Resp.data, "binary");
  const { equal } = await looksSame(img1Buffer, img2Buffer);
  return equal;
};
`

**Comment by DudaGod** [comment]
So I close it.
