### ISSUE TITLE
'ERR_BUFFER_OUT_OF_BOUNDS'

### ISSUE THREAD

**Issue by JattMones** [gemini-testing/looks-same#91]
I've noticed some inconsistent test behavior when running screenshots.js:60 `const diff = await looksSame(testFile, baselineFile, {tolerance: 20})`

I receive the following error message on a particular webpage when running my tests:

```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:399:5)
    at boundsError (node:internal/buffer:86:11)
    at Buffer.readUInt32BE (node:internal/buffer:311:5)
    at get width [as width] (C:\...\node_modules\looks-same\lib\img-buffer\original-buffer.js:14:29)
    at looksSame (C:\...\node_modules\looks-same\index.js:159:41)
    at async C:\...\screenshots.js:60:30 {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

Has this issue been previously reported? It's unclear why this occurs for a particular test/webpage and not others?

**Comment by DudaGod** [comment]
Hello.

Can you provide a minimal case to reproduce it?

Thank you.

**Comment by JattMones** [comment]
Hi,

I figured out the issue. I was trying to compare a list of files (most of them `.jpg`), but a `.txt` file also ended up in the list. That was causing this error to be displayed.
